version: '3'
services:
  frontend:
    build:
      #./something if its in somewhere else
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
        - /app/node_modules
        #. means current folder
        - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]